import { ref } from 'vue';

const paths = {
  1: 'photos',
  3: 'files',
  4: 'videos',
  5: 'animations',
};

const message = {
  id: 1599246,
  title: 'Сообщение c анимацией(gif)',
  text: '<span class="tg-spoiler" style="color:red" >проверка работы</span>',
  text_length: 1024,
  photos: {
    id: 335890,
    code: 'AgACAgQAAxkDAAEDClllPXaJq2M-zv24wknJL-rpb2rYdAAC67ExG1jY5FFTHGYWn110DwEAAwIAA3MAAzAE',
    host: '230925_podpiskabotpng.png',
    abs_path:
      'https://storage.yandexcloud.net/bottstorage/bot/886/photos/afzalov29101701.jpg',
    is_disable_notification: null,
    is_protect_content: null,
    is_spoiler: null,
  },
  files: null,
  videos: null,
  feedback: null,
  animations: null,
  type: {
    id: 1,
    type: 1,
  },
  color: null,
  specType: {
    id: 1,
    title: '',
  },
  sort: null,
  column_id: null,
  active: false,
  menu: null,
  is_generate_default: false,
  is_copy: true,
  is_support_menu: true,
  support_types: {
    '0': 0,
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
  },
  constants: {
    FIRST_NAME: 'Строго имя пользователя',
    SECOND_NAME: 'Строго фамилия пользователя',
    USER_TELEGRAM_ID: 'Telegram id',
    USERNAME: 'Ник пользователя',
    NAME: 'Имя-ссылка/ник пользователя',
    USER_ID: 'ID пользователя в боте',
    BALANCE: 'Баланс пользователя',
    BALANCE_WITHOUT_CURRENCY: 'Баланс пользователя без значка валюты',
    BOT_USER_CREATED_DATETIME: 'Дата и время регистрации пользователя в боте',
    MESSAGE_TITLE: 'Название сообщения',
    MESSAGE_TYPE: 'Тип сообщения',
  },
  constantAnswers: {
    TITLE: 'Название сообщения',
    ANSWERS: 'Вопросы и ответы',
    TIME_ANSWER: 'Время ответа на вопрос',
    BOT_ID: 'Уникальный идентификатор бота',
    BOT_NAME: 'Ссылка на бота',
    BOT_TITLE: 'Имя бота',
    FIRST_NAME: 'Строго имя пользователя',
    SECOND_NAME: 'Строго фамилия пользователя',
    USER_TELEGRAM_ID: 'Telegram id',
    USERNAME: 'Ник пользователя',
    NAME: 'Имя-ссылка/ник пользователя',
  },
  faq: '<br><a href="https://bot-t.com/faq/HELP/tipy_soobshcheniy"><b>Полная информация по свободным кнопкам</b></a>',
};

export const config = ref({
  host: 'https://api.bot-t.com/',
  bot: {
    id: 886,
    user_id: 2371733,
    name: 'shop1_bot_t_ru_bot',
    token: '1172473489:AAFoRo3JvyXS5c1l5aW5qvOtDzZEQVJvf0w',
    type: 2,
    status: 1,
    paid_date: '2023-12-04',
    title: 'Пример магазина №1 BoT-T.ru',
    model_id: 901,
    notice_new_user: 0,
    notice_new_deal: 1,
    created_at: '2020-09-28',
    hello_id: 49,
    tariff_id: 4,
    language_id: 1,
    default_menu_id: 26698,
    error_id: 230331,
    currency_id: 1,
    payment_id: 4977,
    profile_id: 307363,
    time_zone: 1,
    recurrent_check_id: null,
    is_free: null,
  },
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  query: paths[message?.type?.id] ?? 'photos',
  message: message,
  dialog: true,
});
